### ISSUE TITLE
Uncaught TypeError: Cannot read property 'functions' of undefined

### ISSUE THREAD

**Issue by akscanb** [AustP/autocomplete-solidity#2] opened 2016-06-21 21:52 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [autocomplete-solidity](https://github.com/austp/autocomplete-solidity) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'functions' of undefined

```
At /home/god/.atom/packages/autocomplete-solidity/src/util/parser.js:233

TypeError: Cannot read property 'functions' of undefined
    at _parse (/home/god/.atom/packages/autocomplete-solidity/src/util/parser.js:233:46)
    at Object.parse (/home/god/.atom/packages/autocomplete-solidity/src/util/parser.js:558:33)
    at parse (/home/god/.atom/packages/autocomplete-solidity/src/autocomplete-solidity.js:36:28)
    at /home/god/.atom/packages/autocomplete-solidity/src/autocomplete-solidity.js:42:61
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```
### Commands

```
     -2:02.6.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:58.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:51.2.0 tree-view:remove (li.file.entry.list-item.status-added.selected)
     -1:46.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:42 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:40 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:27.8.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:26 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:22.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:11.8.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-solidity, v0.3.0
javascript-snippets, v1.2.1
linter-solidity, v0.2.1

# Dev
No dev packages
```

**Comment by AustP** [comment] 2016-06-23 15:15
Do you have steps to reproduce or perhaps the code you are editing when this happens?

**Comment by akscanb** [comment] 2016-07-03 23:10
Seems like my version of atom was extremely out of date.

**Comment by AustP** [comment] 2016-07-05 20:23
Ok, I'll close this then. Let me know if you run into any other issues!

**Comment by tjayrush** [comment] 2016-08-15 10:43
I have an up-to-date version of Atom (1.9.8). I get this error when I do this:
1. Type an if test for example: if (nTries[msg.sender] > maxTries)
2. Press enter to make a new line and type an opening bracket '{'
3. Auto complete produces the closing bracket (all good so far)

then, just by habit,
1. I press enter again and type another closing bracket.

I shouldn't do this, but I do anyway because when I first learned to code, editors didn't automatically close brackets and I still haven't gotten used to it. I usually just delete the extra closing bracket.

The autocomplete produces this exact error, which seems a bit overbearing to me. At best it should stay silent until I leave the line with the extra bracket (which I don't because I delete the extra bracket right away).

**Comment by AustP** [comment] 2016-08-15 16:50
I'm sorry for the issue @tjayrush. I'll look into this in a couple hours and keep you posted.

**Comment by AustP** [comment] 2016-08-15 23:03
@tjayrush I just pushed version 0.3.3. Does this fix the issue for you?

**Comment by tjayrush** [comment] 2016-08-16 12:37
I appologize. I don't know how to upgrade the installation. Perhaps a short burst in the README.md about installing. I know I already installed this once, but I don't remember what I did.

**Comment by AustP** [comment] 2016-08-16 15:36
@tjayrush I always update my packages through Atom's settings page. `Ctrl+,` is the default binding to open that page then I navigate to Updates.

However, I believe from the command line that you can do `apm upgrade autocomplete-solidity`.

**Comment by tjayrush** [comment] 2016-08-16 17:00
I got it. I tried to reproduce it and it seems to be gone. If it shows up again, I will let you know. I think you can close this. Thanks for fast response.

**Comment by AustP** [comment] 2016-08-16 17:22
Perfect, thanks!

**Closed as completed by AustP** 2016-08-16 17:22 UTC
